name: droute_driver_frontend
description: "This is a Driver Dashboard of dRoute"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.0.1
  google_maps_flutter: ^2.10.0
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  android_icon: "launcher_icon"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/droute_logo.png
    - assets/images/MapMarker.png
